### PR TITLE
ocdav: handle redirection prefixes when extracting destination from URL

### LINKED ISSUE #1104: Reva create error when upload empty file when TUS is enabled
I tried to upload empty file to Reva when TUS is enabled.
It’s necessary because JupyterLab try to upload empty file when create new file.

Riva version: commit 55bfeb6bfd7232e0df3ed79dda1c568501eb2c27 
Default config from: examples/ocmd/ocmd-server-1.toml

Step to reproduce:
```
touch zero.txt
echo "Test" > non_zero.txt
./reva --insecure login basic
```

Creates an error:
```
./reva --insecure upload ./zero.txt /home/zero.txt
Local file size: 0 bytes
Data server: http://localhost:19001/data/da4b3114-672d-4bf7-9495-484e41816973
Allowed checksums: [type:RESOURCE_CHECKSUM_TYPE_MD5 priority:100  type:RESOURCE_CHECKSUM_TYPE_UNSET priority:1000 ]
Checksum selected: RESOURCE_CHECKSUM_TYPE_MD5
Local XS: RESOURCE_CHECKSUM_TYPE_MD5:d41d8cd98f00b204e9800998ecf8427e
 0 B / ? [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------=] 0s
error: code=CODE_NOT_FOUND msg="file not found" support_trace="ec271773afd25787ea2b3b5ca7d6d688"
```

It’s works:
```
./reva --insecure upload ./non_zero.txt /home/non_zero.txt
Local file size: 5 bytes
Data server: http://localhost:19001/data/5e159493-7bf0-4aed-8f6f-b27ead52ad7f
Allowed checksums: [type:RESOURCE_CHECKSUM_TYPE_MD5 priority:100  type:RESOURCE_CHECKSUM_TYPE_UNSET priority:1000 ]
Checksum selected: RESOURCE_CHECKSUM_TYPE_MD5
Local XS: RESOURCE_CHECKSUM_TYPE_MD5:2205e48de5f93c784733ffcca841d2b5
 5 B / 5 B [=====================================================================================================================================================================================================================] 100.00% 0s
File uploaded: 123e4567-e89b-12d3-a456-426655440000:fileid-einstein%2Fnon_zero.txt 5 /home/non_zero.txt
```

### PR DESCRIPTION
**Pull request by ishank011**
The move, copy and trashbin function handler in ocdav extract the destination path from the URL by removing the base URL prefix from the URL path. This would fail in case there is a redirection prefix. This PR takes care of that.

It also allows zero-size uploads for localfs; closes #1104

### CODE REVIEW

File: internal/http/services/owncloud/ocdav/copy.go [hunk 1]
```diff
@@ -123,8 +123,14 @@ func (s *svc) handleCopy(w http.ResponseWriter, r *http.Request, ns string) {
 	}
 
 	// TODO check if path is on same storage, return 502 on problems, see https://tools.ietf.org/html/rfc4918#section-9.9.4
+	// The base URI might contain redirection prefixes which need to be handled
+	urlSplit := strings.Split(urlPath, baseURI)
```
Comment (labkode) [inline internal/http/services/owncloud/ocdav/copy.go:127]: @ishank011 can we create a method for this so is more semantic?

**Review by labkode — APPROVED** [review]
