### PR TITLE
Handle metadata operations for shared folder

### LINKED ISSUE #495: eos: implement virtual shared folder
Implement virtual share folder behaviour by relying on the read amplification model.
The virtual overlay ETAG for the root folder (/home) and the shared folder (/home/MyShares) is done by the gateway to avoid client-side developments for the time being.

On an empty path:
```
EOS Console [root://localhost] |/eos/test/reva/> find .
/eos/test/reva/
```
The user logs in:

```
[gonzalhu@iota reva]$ reva login basic                                                                                                                                                                                                                                                                                                                                                      
username: gonzalhu
password: OK
```

The user real and shadow homedirectories are created. The shadow homedir contains a MyShares folder that will contain the references for all the shares of the user. 

```
EOS Console [root://localhost] |/eos/test/reva/> find .
/eos/test/reva/
/eos/test/reva/users/
/eos/test/reva/users/.shadow/
/eos/test/reva/users/.shadow/g/
/eos/test/reva/users/.shadow/g/gonzalhu/
/eos/test/reva/users/.shadow/g/gonzalhu/MyShares/
/eos/test/reva/users/g/
/eos/test/reva/users/g/gonzalhu/
```

The user cannot fiddle around with the MyShares virtual folder:
```
[gonzalhu@iota reva]$ reva mkdir /home/MyShares
error: code=CODE_INTERNAL msg="error creating container: path:\"/home/MyShares\" " support_trace="b5c8092eb5a8f80db30f7f5b30d25fda"

7:24PM ERR home/gonzalhu/dev/reva/internal/grpc/services/storageprovider/storageprovider.go:342 > error creating container: path:"/home/MyShares"  error="error: permission denied: eos: cannot create folder under the share folder" pid=8931 pkg=rgrpc traceid=b5c8092eb5a8f80db30f7f5b30d25fda

```

The shadow cannot be accessed by users.

### PR DESCRIPTION
**Pull request by labkode**
Fixes #495 

Operations:
- [x] stat
- [x] list container
- [x] move
- [x] delete
- [x] mkdir
- [x] upload
- [x] download

Fixes also #611 

ETAG generation for shared folder covered in:
#612 

Allows to:

```
[gonzalhu@iota reva]$ reva ls /home/MyShares/
[gonzalhu@iota reva]$ reva share-update-received -state accepted 2a023c6b-1bd1-4284-a7d2-343c7ca092af
OK
[gonzalhu@iota reva]$ reva ls /home/MyShares/
photos
[gonzalhu@iota reva]$ reva ls /home/MyShares/photos/
Vigo
test

[gonzalhu@iota reva]$ reva mkdir /home/MyShares/photos/Ourense
[gonzalhu@iota reva]$ reva ls /home/MyShares/photos/
Ourense
Vigo
```

### CODE REVIEW

**Comment by labkode** [comment]
@butonic can you review the current state, I prefer to merge and create another PR for the upload and download parts like that we can already mount/unmount access shares in the user home.

**Comment by butonic** [comment]
@refs this is related to the /s/ prefix you were using for the public shares provider. Adding a GetPublicShares to the cs3 api seems to leak implementation details AFAICT ...

This PR hardcodes the /home path in the global namespace.

**Comment by labkode** [comment]
@butonic merged, I also add the upload/download methods.

File: internal/grpc/services/gateway/storageprovider.go [hunk 1]
```diff
@@ -440,6 +1015,274 @@ func (s *svc) ListContainer(ctx context.Context, req *provider.ListContainerRequ
...
+func (s *svc) split(ctx context.Context, p string, i int) bool {
+	log := appctx.GetLogger(ctx)
+	if i < 2 {
+		panic("split called with i < 2")
+	}
+
+	parts := s.splitPath(ctx, p)
+
+	// validate that we have always at least two elements
+	if len(parts) < 2 {
```
Comment (butonic) [inline internal/grpc/services/gateway/storageprovider.go]: there might be only one part when stating `/home` ... which happens on every propfind.
```
10:40PM ERR home/jfd/Repositories/reva/internal/grpc/interceptors/recovery/recovery.go:50 > split: len(parts) < 2: path:/home parts:[home]
```

Comment (labkode) [reply internal/grpc/services/gateway/storageprovider.go]: can you try with master ? shouldn't happen, listing /home is okay?

Comment (butonic) [reply internal/grpc/services/gateway/storageprovider.go:1243]: this is master:
```go
	// validate that we have always at least two elements
	if len(parts) < 2 {
		panic(fmt.Sprintf("split: len(parts) < 2: path:%s parts:%+v", p, parts))
	}
```
The logic does not work out when stating `/home` because trimmed for `/` it is just `home` and that has only one path segment, not two.

Comment (butonic) [reply internal/grpc/services/gateway/storageprovider.go:1243]: might be caused by not having set a `share_folder` ... checking

Comment (butonic) [reply internal/grpc/services/gateway/storageprovider.go:1243]: ok, i can do propfinds when specifying an explicit `share_folder`
